#!/bin/bash

docker pull clickhouse/clickhouse-server:23.8.14.6
docker pull hmisecmis/jempi-bootstrapper:sd-dev
docker pull jembi/jempi-api:1.1.1
docker pull hmisecmis/jempi-async-receiver:sd-dev
docker pull jembi/jempi-etl:1.1.0
docker pull jembi/jempi-controller:1.1.0
docker pull jembi/jempi-em-scala:dev
docker pull jembi/jempi-linker:1.1.1
docker pull jembi/jempi-web:1.1.0
docker pull apache/superset:3.1.1
docker pull dgraph/dgraph:v23.1.1
docker pull dgraph/ratel:v21.03.2
docker pull bitnamilegacy/postgresql-repmgr:14
docker pull bitnami/pgpool:4.4.3
docker pull jembi/hapi:v7.0.3-wget
docker pull jembi/fhir-ig-importer-mediator:latest
docker pull jembi/fhir-ig-importer-mediator-ui:latest
docker pull keycloak/keycloak:20.0
docker pull jembi/openhim-core:v8.5.0
docker pull jembi/openhim-console:v1.18.2
docker pull mongo:4.2
docker pull jembi/await-helper:1.0.1
docker pull mcuadros/ofelia:v0.3.6
docker pull jembi/kafka-mapper-consumer:v1.1.0
docker pull jembi/kafka-mapper-consumer-ui:v1.1.0
docekr pull jembi/kafka-unbundler-consumer:0.0.3
docker pull bitnamilegacy/kafka:3.4.0
docker pull obsidiandynamics/kafdrop:3.27.0
docker pull quay.io/cloudhut/kminion:master
docker pull prom/prometheus:v2.38.0
docker pull gcr.io/cadvisor/cadvisor:v0.45.0
docker pull quay.io/prometheus/node-exporter:v1.3.1
docker pull quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
docker pull grafana/grafana-oss:9.2.3
docker pull grafana/loki:2.6.1
docker pull grafana/promtail:2.6.1
docker pull prom/prometheus:v2.38.0
docker pull node:erbium-alpine
docker pull jembi/mpi-mediator:v2.3.1
docker pull jembi/openhim-mediator-mapping:v3.3.0
docker pull jembi/reprocess-mediator:latest
docker pull jembi/reprocess-mediator-ui:latest
docker pull nginx:stable
