upstream dgraph_alpha {
    least_conn;
    #ip_hash;
    server jempi-alpha-01:8080;
    server jempi-alpha-02:8080;
    server jempi-alpha-03:8080;
}

upstream dgraph_grpc {
    least_conn;
    #ip_hash;
    server jempi-alpha-01:9080;
    server jempi-alpha-02:9080;
    server jempi-alpha-03:9080;
}

# Dgraph http server config
server {
    listen          9085;

    location / {
        resolver    127.0.0.11 valid=30s;
        proxy_pass  http://dgraph_alpha;
    }
}

# Dgraph grpc server config
server {
    listen          9086 http2;

    location / {
        grpc_pass  grpc://dgraph_grpc;
    }
}

# Ratel server config
server {
    listen          8010;

    location / {
        resolver    127.0.0.11 valid=30s;
        set         $upstream_ratel jempi-ratel;
        proxy_pass  http://$upstream_ratel:8000;
    }
}
