version: "3.9"

services:
  mpi-mediator:
    image: jempi/mpi-mediator:latest
    networks:
      openhim:
      kafka:
      clickhouse:
      public:
      default:
    environment:
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      MPI_PROTOCOL: ${MPI_PROTOCOL}
      MPI_HOST: ${MPI_HOST}
      MPI_PORT: ${MPI_PORT}
      MPI_CLIENT_ID: ${MPI_CLIENT_ID}
      MPI_CLIENT_SECRET: ${MPI_CLIENT_SECRET}
      MPI_AUTH_ENABLED: ${MPI_AUTH_ENABLED}
      MPI_PROXY_URL: ${MPI_PROXY_URL}
      KAFKA_BROKERS: ${KAFKA_HOSTS}
      KAFKA_BUNDLE_TOPIC: ${KAFKA_BUNDLE_TOPIC}
      KAFKA_ASYNC_BUNDLE_TOPIC: ${KAFKA_ASYNC_BUNDLE_TOPIC}
      KAFKA_ERROR_TOPIC: ${KAFKA_ERROR_TOPIC}
      FHIR_DATASTORE_PROTOCOL: ${FHIR_DATASTORE_PROTOCOL}
      FHIR_DATASTORE_HOST: ${FHIR_DATASTORE_HOST}
      FHIR_DATASTORE_PORT: ${FHIR_DATASTORE_PORT}
      DISABLE_VALIDATION: ${DISABLE_VALIDATION}
      ENABLE_JEMPI_GOLDEN_ID_UPDATE: ${ENABLE_JEMPI_GOLDEN_ID_UPDATE}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      PATIENT_PROFILE_FOR_STUB_PATIENT: ${PATIENT_PROFILE_FOR_STUB_PATIENT}
    deploy:
      placement:
        max_replicas_per_node: ${MPI_MEDIATOR_MAX_REPLICAS_PER_NODE}
      replicas: ${MPI_MEDIATOR_INSTANCES}

networks:
  openhim:
    name: openhim_public
    external: true
  kafka:
    name: kafka_public
    external: true
  clickhouse:
    name: clickhouse_public
    external: true
  public:
    name: mpi_public
    external: true
  default:
